user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

base:
    resource: @BaseBundle/Controller/
    type:     annotation

base2:
    resource: "@BaseBundle/Resources/config/routing.yml"
    prefix: /

project:
    resource: @ProjectBundle/Controller/
    type:     annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /inbox

profil:
    resource: @UserBundle/Controller/
    type:     annotation