ProjectBundle\Entity\FavoritedProject:
    type: entity
    table: favoritedProject
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: userId
        projectId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: projectId
    lifecycleCallbacks: {  }
