<?php

namespace ProjectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{	
	public function index4projets() {
		
		
		$qb = $this->createQueryBuilder('p')

				  ->orderBy('p.beginDate', 'DESC')

				  ->setMaxResults(3)
				  
				  ->getQuery()
				  
				  ->getResult();
				  
	
		
		return $qb;
		
	}
}
